"""Plan-as-IKAM primitives.

This module defines the canonical JSON plan schema and deterministic serialization
used to produce stable CAS bytes and stable plan artifact IDs.

Design constraints:
- Deterministic: equivalent plan objects → identical canonical bytes
- No chain-of-thought: plans and amendments store only structured fields
"""

from modelado.plans.amendments import (
    apply_plan_amendment,
    apply_plan_amendments,
    apply_petri_net_amendment,
    apply_plan_patch,
    validate_petri_plan_patch_ops,
)
from modelado.plans.artifacts import (
    plan_to_ikam_artifact,
    reconstruct_plan_from_fragments,
    reconstruct_petri_net_from_fragments,
    plan_amendment_to_ikam_artifact,
    petri_net_to_ikam_artifact,
    petri_run_to_ikam_artifact,
)
from modelado.plans.persistence import (
    persist_plan,
    persist_plan_amendment,
    persist_plan_amendment_application,
    persist_plan_verification_report,
    persist_plan_in_scope,
    persist_petri_net,
    persist_petri_net_run,
    create_root_plan_net,
)
from modelado.plans.events import (
    PLAN_EVENT_SCHEMA_VERSION,
    PlanLease,
    PlanLeaseState,
    build_plan_event,
    canonicalize_json,
    get_effective_lease,
    plan_event_id,
    reduce_plan_events,
)
from modelado.plans.schema import (
    ArtifactRef,
    FailurePath,
    Milestone,
    Plan,
    PlanAmendment,
    PlanPatchOp,
    PlanRef,
    Validation,
    PetriNetArc,
    PetriNetArcEndpoint,
    PetriNetEnvelope,
    PetriNetMarking,
    PetriNetPlace,
    PetriNetSection,
    PetriNetTransition,
    PetriNetRunEnvelope,
    PetriNetRunFiring,
    PlanTransitionRef,
    normalize_plan_ref,
    plan_ref_from_metadata,
    canonicalize_plan_json,
    canonicalize_plan_amendment_json,
    canonicalize_petri_net_arc_json,
    canonicalize_petri_net_envelope_json,
    canonicalize_petri_net_marking_json,
    canonicalize_petri_net_place_json,
    canonicalize_petri_net_section_json,
    canonicalize_petri_net_transition_json,
    canonicalize_petri_run_envelope_json,
    canonicalize_petri_run_firing_json,
    amendment_artifact_uuid,
    plan_artifact_uuid,
    petri_net_artifact_uuid,
    petri_run_artifact_uuid,
    plan_cas_id,
    require_non_negative_marking,
    require_transition_place_refs,
    require_unique_place_ids,
    require_unique_transition_ids,
)
from modelado.plans.verification import (
    PLAN_VERIFICATION_REPORT_SCHEMA_ID,
    PlanVerificationReport,
    canonicalize_plan_verification_report_json,
)
from modelado.plans.plan_run_edges import (
    append_plan_run_of_edge,
    append_fired_transition_edge,
    append_derived_from_edges,
)

__all__ = [
    "ArtifactRef",
    "FailurePath",
    "Milestone",
    "Plan",
    "PlanAmendment",
    "PlanPatchOp",
    "PlanRef",
    "PetriNetArc",
    "normalize_plan_ref",
    "plan_ref_from_metadata",
    "PetriNetArcEndpoint",
    "PetriNetEnvelope",
    "PetriNetMarking",
    "PetriNetPlace",
    "PetriNetSection",
    "PetriNetTransition",
    "PetriNetRunEnvelope",
    "PetriNetRunFiring",
    "PlanTransitionRef",
    "Validation",
    "apply_plan_amendment",
    "apply_plan_amendments",
    "apply_petri_net_amendment",
    "apply_plan_patch",
    "validate_petri_plan_patch_ops",
    "canonicalize_petri_net_arc_json",
    "canonicalize_petri_net_envelope_json",
    "canonicalize_petri_net_marking_json",
    "canonicalize_petri_net_place_json",
    "canonicalize_petri_net_section_json",
    "canonicalize_petri_net_transition_json",
    "canonicalize_petri_run_envelope_json",
    "canonicalize_petri_run_firing_json",
    "canonicalize_plan_json",
    "canonicalize_plan_amendment_json",
    "canonicalize_json",
    "require_unique_place_ids",
    "require_unique_transition_ids",
    "require_transition_place_refs",
    "require_non_negative_marking",
    "amendment_artifact_uuid",
    "plan_to_ikam_artifact",
    "reconstruct_plan_from_fragments",
    "reconstruct_petri_net_from_fragments",
    "plan_amendment_to_ikam_artifact",
    "petri_net_to_ikam_artifact",
    "petri_run_to_ikam_artifact",
    "persist_plan",
    "persist_plan_amendment",
    "persist_plan_amendment_application",
    "persist_plan_verification_report",
    "persist_plan_in_scope",
    "persist_petri_net",
    "persist_petri_net_run",
    "create_root_plan_net",
    "plan_artifact_uuid",
    "petri_net_artifact_uuid",
    "petri_run_artifact_uuid",
    "plan_cas_id",
    "PLAN_EVENT_SCHEMA_VERSION",
    "PlanLease",
    "PlanLeaseState",
    "build_plan_event",
    "get_effective_lease",
    "plan_event_id",
    "reduce_plan_events",

    "PLAN_VERIFICATION_REPORT_SCHEMA_ID",
    "PlanVerificationReport",
    "canonicalize_plan_verification_report_json",

    "append_plan_run_of_edge",
    "append_fired_transition_edge",
    "append_derived_from_edges",
]
